/* Data Warehouse DDL Demonstration */

/* Create new tablespace */
CREATE TABLESPACE DM_DATA
  DATAFILE 'dm_data.dat'
  SIZE 20M AUTOEXTEND ON;

/* Create New Table for OJK-BOX Data Mart */
CREATE TABLE "DMDEV"."OJKBOX_DTL_NO01" 
   (	"BASE_DT" CHAR(8 BYTE), 
	"COST_CNTR" VARCHAR2(11 BYTE), 
	"BO_DEAL_NO" VARCHAR2(15 BYTE), 
	"CUST_FULL_NM1" VARCHAR2(35 BYTE), 
	"STATUS" CHAR(3 BYTE), 
	"STD_INDS_CD_ID" VARCHAR2(25 BYTE), 
	"COUNTRY_ABBR" CHAR(3 BYTE), 
	"TX_AMT_IDR" NUMBER(19,2), 
	"TX_AMT_USD" NUMBER(19,2), 
	"IDR_XRT" NUMBER(19,2), 
	"APPL" CHAR(2 BYTE),
  	"FO_DEAL_NO" VARCHAR2(10 BYTE),
	"ORG_PRC_DT" CHAR(8 BYTE), 
	"CPY_DT" CHAR(8 BYTE), 
	"CPY_TM" CHAR(6 BYTE), 
	"LST_MDFCPY_DT" CHAR(8 BYTE), 
	"LST_MDFCPY_TM" CHAR(6 BYTE)
   )
/* Specify tablespace and partition with range approach */   
TABLESPACE DM_DATA
PARTITION BY RANGE (BASE_DT) (
  PARTITION OJKBOX_DTL_NO01_1912 VALUES LESS THAN ('20200101') NO INMEMORY SEGMENT CREATION IMMEDIATE,
  PARTITION OJKBOX_DTL_NO01_2012 VALUES LESS THAN ('20210101') NO INMEMORY SEGMENT CREATION IMMEDIATE
);

/* Create Partitioning Index */
CREATE INDEX "DMDEV"."OJKBOX_DTL_NO01_I1" ON "DMDEV"."OJKBOX_DTL_NO01" ("BASE_DT") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
 (PARTITION "OJKBOX_DTL_NO01_1912"
  TABLESPACE "DM_DATA" , 
 PARTITION "OJKBOX_DTL_NO01_2012" 
  TABLESPACE "DM_DATA"
 ) ;

/* TO-DO: Create New Table Customer */ -- to demonstrate join dml

/* TO-DO: Create New Table SUM */ -- to demonstrate aggregation query
